# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: validate-composer-json
        name: Validate Composer JSON
        entry: "composer validate"
        language: system
        files: composer\.json

      - id: check-js-debug
        name: Check javascript debug statements
        language: pygrep
        entry: '\b(console\s*\.\s*debug|console\s*\.\s*log)\s*\('
        files: resources/js/.*\.(js|html|vue)$

      - id: js-lint
        name: Run ESLint fixer
        language: system
        entry: './node_modules/.bin/eslint --fix'
        files: resources/js/.*\.(js)$

  - repo: https://github.com/motivozwolle/pre-commit-hooks
    rev: v1.0.2
    hooks:
      - id: add-ticket-to-commit

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: check-xml
      - id: check-merge-conflict

default_stages:
  - commit
