name: Clean up PR title

author: Sibi B.V.

description: |
  Cleans up pull requests titles and adds Jira ticket numbers

inputs:
  token:
    description: GitHub access token, required
    required: true
  ticket-number:
    description: Ticket number to override
    required: false
    default: ''
  label:
    description: Defines if the PR should be labeled
    required: false
    default: true

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: edit-2
  color: blue
