name: Update PR details

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  fix-pr:
    name: Update PR details
    runs-on: ubuntu-latest

    steps:
      - name: Update PR
        uses: sibizwolle/fix-title@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: true
