name: Compile action

on:
  push:
    branches:
      - master
    paths:
      - index.js
      - package.json
      - lib/

jobs:
  build-with-ncs:
    name: Build action with ncc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Test output
        run: npm run test

      - name: Build action
        run: |
          rm -rf dist/
          npm run build

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Compiled action using GitHub Actions'
          file_pattern: 'dist/*'
          add_options: '-f'
          skip_dirty_check: true
